import httpx
import asyncio
import json
from typing import Optional
from abc import ABC, abstractmethod

class BaseProvider(ABC):
    @abstractmethod
    async def connect(self):
        pass

    @abstractmethod
    async def disconnect(self):
        pass

    @abstractmethod
    async def healthcheck(self) -> bool:
        pass

    @abstractmethod
    async def chat(self, model: str, system_prompt: str, user_prompt: str, agent_id: Optional[str] = None, max_tokens: int = 4096) -> str:
        pass

    @abstractmethod
    async def tool_call(self):
        pass

    @abstractmethod
    async def stream(self):
        pass

class OpenAICompatibleProvider(BaseProvider):
    # Global lock to prevent LM Studio / Local models from crashing due to context switching
    _lock = asyncio.Lock()

    def __init__(self, base_url: str, api_key: str = "lm-studio"):
        self.base_url = base_url
        self.api_key = api_key
        limits = httpx.Limits(max_keepalive_connections=5, max_connections=10)
        self.client = httpx.AsyncClient(
            base_url=self.base_url,
            limits=limits,
            timeout=httpx.Timeout(120.0, connect=10.0),
            headers={"Authorization": f"Bearer {self.api_key}"}
        )

    async def connect(self):
        pass

    async def disconnect(self):
        await self.client.aclose()

    async def healthcheck(self) -> bool:
        try:
            res = await self.client.get("/models")
            return res.status_code == 200
        except Exception:
            return False

    async def chat(self, model: str, system_prompt: str, user_prompt: str, agent_id: Optional[str] = None, max_tokens: int = 4096) -> str:
        async with self._lock:
            try:
                payload = {
                    "model": model,
                    "messages": [
                        {"role": "system", "content": system_prompt},
                        {"role": "user", "content": user_prompt}
                    ],
                    "temperature": 0.7,
                    "max_tokens": max_tokens,
                    "stream": False
                }
                
                response = await self.client.post("/chat/completions", json=payload)
                
                if response.status_code == 200:
                    return response.json()["choices"][0]["message"]["content"]
                return f"AI Provider Error ({response.status_code}): {response.text}"
                
            except httpx.ReadTimeout:
                return "AI Timeout: The model took too long to respond."
            except httpx.ConnectError:
                return f"Connection Error: Cannot connect to {self.base_url}."
            except Exception as e:
                return f"Unexpected Error: {str(e)}"

    async def tool_call(self):
        pass

    async def stream(self):
        pass

class GeminiProvider(BaseProvider):
    def __init__(self, api_key: str):
        self.api_key = api_key
        self.base_url = "https://generativelanguage.googleapis.com/v1beta/models"
        limits = httpx.Limits(max_keepalive_connections=5, max_connections=10)
        self.client = httpx.AsyncClient(limits=limits, timeout=httpx.Timeout(60.0))

    async def connect(self):
        pass

    async def disconnect(self):
        await self.client.aclose()

    async def healthcheck(self) -> bool:
        try:
            res = await self.client.get(f"{self.base_url}?key={self.api_key}")
            return res.status_code == 200
        except Exception:
            return False

    async def chat(self, model: str, system_prompt: str, user_prompt: str, agent_id: Optional[str] = None, max_tokens: int = 4096) -> str:
        try:
            # Gemini URL format: /models/{model}:generateContent
            url = f"{self.base_url}/{model}:generateContent?key={self.api_key}"
            payload = {
                "systemInstruction": {
                    "parts": [{"text": system_prompt}]
                },
                "contents": [
                    {
                        "role": "user",
                        "parts": [{"text": user_prompt}]
                    }
                ],
                "generationConfig": {
                    "temperature": 0.7,
                    "maxOutputTokens": max_tokens,
                }
            }
            
            response = await self.client.post(url, json=payload, headers={"Content-Type": "application/json"})
            
            if response.status_code == 200:
                data = response.json()
                if "candidates" in data and len(data["candidates"]) > 0:
                    return data["candidates"][0]["content"]["parts"][0]["text"]
                return "No content generated by Gemini."
            return f"Gemini Error ({response.status_code}): {response.text}"
            
        except Exception as e:
            return f"Unexpected Error: {str(e)}"

    async def tool_call(self):
        pass

    async def stream(self):
        pass

class ProviderFactory:
    @staticmethod
    def create_provider(provider_type: str, base_url: str = None, api_key: str = None) -> BaseProvider:
        provider_type = provider_type.lower()
        openai_types = ["openai_compatible", "lm-studio", "ollama", "openclaw", "hermes"]
        if provider_type in openai_types:
            return OpenAICompatibleProvider(base_url=base_url, api_key=api_key or "lm-studio")
        elif provider_type == "gemini":
            if not api_key:
                raise ValueError("API Key is required for Gemini Provider")
            return GeminiProvider(api_key=api_key)
        else:
            raise ValueError(f"Unknown provider type: {provider_type}")